---
title: "get data from calender"
author: "Christara Laing"
date: "2023-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(toastui)
```



<button type="button">Click Me!</button>
```{r}
gc_events <- read_csv("~/calender/CalendarWiz_Export (2).csv")

glimpse(gc_events)

fixed <- gc_events %>% 
  mutate(is_holiday = case_when(TRUE == str_detect(Subject, "[Hh]oliday") ~ "yes",
                               FALSE == str_detect(Subject, "[Hh]oliday") ~ "no")) %>% 
  mutate(body = Description,
         title = Subject,
         title = str_replace_all(Subject, "\\\x94 | \\?", ""),
         location = Location,
         date = as_date(`Start Date`, "%d/%m/%Y")) %>% 
         unite(start1, c(`Start Date`, `Start Time`), sep = " ", remove = FALSE) %>% 
         unite(end1, c(`End Date`, `End Time`), sep = " ", remove = FALSE) %>% 
         mutate(start = dmy_hms(start1, tz = "UTC"),
                start = format(start, "%Y-%m-%d %H:%M:%S"),
                end = dmy_hms(end1, tz = ""),
                end = format(end, "%Y-%m-%d %H:%M:%S"),
                calendarId = 2,
                id = 2) %>% 
        filter(`All day event` == TRUE) %>% 
        group_by(title, `All day event`) %>% 
        summarise(start = min(ymd_hms(start), na.rm = TRUE),
                  end = max(ymd_hms(end), na.rm = TRUE),
                  location = unique(Location),
                  id = max(id),
                  calenderId = max(id))



all_day_chart <- gc_events %>% 
  mutate(is_holiday = case_when(TRUE == str_detect(Subject, "[Hh]oliday") ~ "yes",
                               FALSE == str_detect(Subject, "[Hh]oliday") ~ "no")) %>% 
  mutate(body = Description,
         title = Subject,
         title = str_replace_all(Subject, "\\\x94 | \\?", ""),
         location = Location,
         date = as_date(`Start Date`, "%d/%m/%Y")) %>% 
         unite(start1, c(`Start Date`, `Start Time`), sep = " ", remove = FALSE) %>% 
         unite(end1, c(`End Date`, `End Time`), sep = " ", remove = FALSE) %>% 
         mutate(start = dmy_hms(start1, tz = "UTC"),
                start = format(start, "%Y-%m-%d %H:%M:%S"),
                end = dmy_hms(end1, tz = ""),
                end = format(end, "%Y-%m-%d %H:%M:%S"),
                calendarId = 2,
                id = 2) %>% 
  filter(`All day event` == TRUE)

all_day <- gc_events %>% 
  mutate(is_holiday = case_when(TRUE == str_detect(Subject, "[Hh]oliday") ~ "yes",
                               FALSE == str_detect(Subject, "[Hh]oliday") ~ "no")) %>% 
  mutate(body = Description,
         title = Subject,
         title = str_replace_all(Subject, "\\\x94 | \\?", ""),
         location = Location,
         date = dmy(`Start Date`)) %>% 
         unite(start1, c(`Start Date`, `Start Time`), sep = " ", remove = FALSE) %>% 
         unite(end1, c(`End Date`, `End Time`), sep = " ", remove = FALSE) %>% 
         mutate(start = dmy_hms(start1, tz = "UTC"),
                start = format(start, "%Y-%m-%d %H:%M:%S"),
                end = dmy_hms(end1, tz = ""),
                end = format(end, "%Y-%m-%d %H:%M:%S"),
                calendarId = 2,
                id = 2) %>% 
  filter(`All day event` == TRUE) %>% 
  mutate(year = year(as.Date(`Start Date`,'%d/%m/%Y'))) %>% 
  group_by(title,`Repeat Id`, year) %>% 
  summarise(start = min(ymd_hms(start)),
            end = max(ymd_hms(end)),
            location = unique(Location),
            id = max(id),
            calenderId = max(id))

```


```{r}
holiday <- function(){
 all_day %>% 
     mutate(is_holiday = case_when(TRUE == str_detect(title, "[Hh]oliday") ~ "yes",
                                 FALSE == str_detect(title, "[Hh]oliday") ~ "no"),
           id = case_when(is_holiday == "yes" ~ 1,
                          is_holiday == "no" ~ 4
                          ),
           calendarId = id) %>% 
    select(title, start, end, calendarId, id) 
}
```


```{r}
gc_cal_data <- function(){
  gc_events %>% 
    mutate(is_holiday = case_when(TRUE == str_detect(Subject, "[Hh]oliday") ~ "yes",
                                 FALSE == str_detect(Subject, "[Hh]oliday") ~ "no"),
           id = case_when(is_holiday == "yes" ~ 1,
                          is_holiday == "no" ~ case_when(Categories == "Art" ~ 3,
                                                         Categories == "Academics" ~ 2,
                                                         Categories == "Equine Scholars" ~ 4,
                                                         .default = 4
                          ))) %>% 
    mutate(body = Description,
           title = Subject,
           title = str_replace_all(Subject, "\\\x94 | \\?", ""),
           location = Location,
           date = as_date(`Start Date`, "%d/%m/%Y")) %>% 
           unite(start1, c(`Start Date`, `Start Time`), sep = " ", remove = FALSE) %>% 
           unite(end1, c(`End Date`, `End Time`), sep = " ", remove = FALSE) %>% 
           mutate(start = dmy_hms(start1, tz = "UTC"),
                  start = format(start, "%Y-%m-%d %H:%M:%S"),
                  end = dmy_hms(end1, tz = ""),
                  end = format(end, "%Y-%m-%d %H:%M:%S"),
                  calendarId = id) %>% 
           select(title, start, location, end, body, calendarId, id) 
}

```

```{r}
"Activities Council"			
"Admissions"
"Alumni"
"Art"			
"Athletic"			
"Calling and Career"			
"Diversity"
"Equine Scholars"		
"External Sponsored Events on Campus"			
"Faith & Service"
"Fitness Center"
"General"			
"Graduate Education"			
"Greek Life"			
"Health and Wellness"
"Holidays & Closing"			
"International Programs"			
"Nexus"		
"Performing Arts"
"Staff & Faculty"
"Student Government Association"	
"Student Life"			
"Summer Camps"
"Undergraduate Education"

calendar_properties

calendar(holiday(), navigation = TRUE) %>% 
  cal_props(cal_demo_props())
```

```{r}
cal_gc_props <- function() {
  props <- list(
    list(
      id = "1",
      name = "Holidays & Closing",
      color = "#000",
      backgroundColor = "lightgray",
      borderColor = "gray"
    ),
    list(
      id = "2",
      name = "Academics",
      color = "#000",
      backgroundColor = "#F5A9A9",
      borderColor = "firebrick"
    ),
    list(
      id = "3",
      name = "Art",
      color = "#000",
      backgroundColor = "#AA336A",
      borderColor = "#702963"
    ),
    list(
      id = "4",
      name = "Equine Scholars",
      color = "#000",
      backgroundColor = "#05CDCD",
      borderColor = "#3b7cc6"
    )
  )
  do.call("rbind", lapply(props, as.data.frame))
}

calendar(gc_cal_data(), navigation = TRUE) %>% 
  cal_props(cal_gc_props())
```



